var Photo_cjl=[
    {
        photoName_cjl:"img01",
        PhotoManagements_cjl: "../images/cjl/1.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"实验室是科学的摇篮",
        photoBan_cjl:"研三",
    },
    {
        photoName_cjl:"img02",
        PhotoManagements_cjl: "../images/cjl/2.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"科研创新的孵化器",
        photoBan_cjl:"研一",
    },
    {
        photoName_cjl:"img03",
        PhotoManagements_cjl: "../images/cjl/3.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"数据分析的中心",
        photoBan_cjl:"研一",
    },
    {
        photoName_cjl:"img04",
        PhotoManagements_cjl: "../images/cjl/4.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"数据分析的中心",
        photoBan_cjl:"研三",
    },
    {
        photoName_cjl:"img05",
        PhotoManagements_cjl: "../images/cjl/5.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"科技的发展源泉",
        photoBan_cjl:"研三",
    },
    {
        photoName_cjl:"img06",
        PhotoManagements_cjl: "../images/cjl/6.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"创新的思想温床",
        photoBan_cjl:"研一",
    },
    {
        photoName_cjl:"img07",
        PhotoManagements_cjl: "../images/cjl/7.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"未来的技术孵化器",
        photoBan_cjl:"研三",
    },
    {
        photoName_cjl:"img08",
        PhotoManagements_cjl: "../images/cjl/8.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"实验室的智慧堆积",
        photoBan_cjl:"研三",
    },
    {
        photoName_cjl:"img09",
        PhotoManagements_cjl: "../images/cjl/9.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"科学家的天堂",
        photoBan_cjl:"研三",
    },
    {
        photoName_cjl:"img10",
        PhotoManagements_cjl: "../images/cjl/10.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"科研项目的基地",
        photoBan_cjl:"研一",
    },
    {
        photoName_cjl:"img11",
        PhotoManagements_cjl: "../images/cjl/11.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"实验数据的秘密所",
        photoBan_cjl:"研三",
    },
    {
        photoName_cjl:"img12",
        PhotoManagements_cjl: "../images/cjl/12.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"知识的发源地",
        photoBan_cjl:"研0",
    },
    {
        photoName_cjl:"img13",
        PhotoManagements_cjl: "../images/cjl/13.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"科学实验的中心",
        photoBan_cjl:"研三",
    },
    {
        photoName_cjl:"img14",
        PhotoManagements_cjl: "../images/cjl/14.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"创新成果的孵化地",
        photoBan_cjl:"研一",
    },
    {
        photoName_cjl:"img15",
        PhotoManagements_cjl: "../images/cjl/15.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"科技研究的大本营",
        photoBan_cjl:"研三",
    },
    {
        photoName_cjl:"img16",
        PhotoManagements_cjl: "../images/cjl/16.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"科研精英的汇聚地",
        photoBan_cjl:"研一",
    },
    {
        photoName_cjl:"img17",
        PhotoManagements_cjl: "../images/cjl/17.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"科学家的精神殿堂",
        photoBan_cjl:"研三",
    },
    {
        photoName_cjl:"img18",
        PhotoManagements_cjl: "../images/cjl/18.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"科学家的精神殿堂",
        photoBan_cjl:"研三",
    },
    {
        photoName_cjl:"img19",
        PhotoManagements_cjl: "../images/cjl/19.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"知识交流的场所",
        photoBan_cjl:"研三",
    },
    {
        photoName_cjl:"img20",
        PhotoManagements_cjl: "../images/cjl/20.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"科研项目的创新源",
        photoBan_cjl:"研一",
    },
    {
        photoName_cjl:"img21",
        PhotoManagements_cjl: "../images/cjl/21.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"科技创新的引擎",
        photoBan_cjl:"研三",
    },
    {
        photoName_cjl:"img22",
        PhotoManagements_cjl: "../images/cjl/22.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"科研成果的孕育地",
        photoBan_cjl:"研三",
    },
    {
        photoName_cjl:"img23",
        PhotoManagements_cjl: "../images/cjl/23.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"实验室的科学殿堂",
        photoBan_cjl:"研三",
    },
    {
        photoName_cjl:"img24",
        PhotoManagements_cjl: "../images/cjl/24.jpg",
        photoHuo_cjl:"实验室",
        photoIntroduction:"创新思维的温床",
        photoBan_cjl:"研三",
    },
]